# Storage account name: 3-24 chars, lowercase alphanumeric only, globally unique.
resource "azurerm_storage_account" "main" {
  name                = "${var.project_name}${var.environment}${random_string.suffix.result}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  account_kind        = "StorageV2"
  account_tier        = "Standard"

  account_replication_type = var.storage_replication_type

  # Security hardening
  https_traffic_only_enabled      = true
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false # No anonymous blob access; uploads use SAS tokens.
  shared_access_key_enabled       = true  # Required for server-side SAS token generation.

  blob_properties {
    # CORS allows the browser to call the Blob service endpoint directly for uploads.
    cors_rule {
      allowed_origins    = var.allowed_origins
      allowed_methods    = ["DELETE", "GET", "HEAD", "MERGE", "OPTIONS", "PATCH", "POST", "PUT"]
      allowed_headers    = ["*"]
      exposed_headers    = ["ETag", "Content-Length", "x-ms-request-id", "x-ms-version"]
      max_age_in_seconds = 3600
    }

    delete_retention_policy {
      days = 7
    }
  }

  tags = local.common_tags
}

resource "azurerm_storage_container" "media" {
  name               = "bridgedrop-media"
  storage_account_id = azurerm_storage_account.main.id

  # Private: all access goes through SAS tokens generated by your backend.
  container_access_type = "private"
}
